#!/usr/bin/env python3

"""
This module defines a function for collecting the results of
the async_generator function and returns them
"""

from asyncio import sleep
from random import uniform
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    The function uses an async generator and
    retruns a list of items generated by the function
    """
    return [i async for i in async_generator()]
